spring:
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://postgresql-db:5432/articledb
    driver-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 1812
