spring:
  application:
    name: authentication
  datasource:
    url: jdbc:postgresql://postgresql-db:5432/articledb
    driver-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: "http://eureka-server:8761/eureka/"
server:
  port: 1812
